services:
  nextjs:
    build:
      context: ./apps/nextjs-web
      dockerfile: ../../docker/development/nextjs.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/nextjs-web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1

  python-api:
    build:
      context: ./apps/python-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/python-api:/app
    environment:
      - ENVIRONMENT=development
    env_file:
      - ./apps/python-api/.env
    depends_on:
      - nextjs
