services:
  nextjs:
    build:
      context: ./apps/nextjs-web
      dockerfile: ../../docker/development/nextjs.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/nextjs-web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
