name: Python API CI

on:
  push:
    paths:
      - 'apps/python-api/**'
    branches:
      - main
  pull_request:
    paths:
      - 'apps/python-api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/python-api

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        echo "Tests coming soon" 